var users = ["http://dubai.flywheelsports.com/class/25087",
            "http://dubai.flywheelsports.com/class/25088",
            "http://dubai.flywheelsports.com/class/25089",
            "http://dubai.flywheelsports.com/class/25090",
            "http://dubai.flywheelsports.com/class/25091",
            "http://dubai.flywheelsports.com/class/25092",
            "http://dubai.flywheelsports.com/class/25093",
            "http://dubai.flywheelsports.com/class/25094",
            "http://dubai.flywheelsports.com/class/25095",
            "http://dubai.flywheelsports.com/class/25096",
            "http://dubai.flywheelsports.com/class/25097",
            "http://dubai.flywheelsports.com/class/25098",
            "http://dubai.flywheelsports.com/class/25099",
            "http://dubai.flywheelsports.com/class/25100",
            "http://dubai.flywheelsports.com/class/25101",
            "http://dubai.flywheelsports.com/class/25102",
            "http://dubai.flywheelsports.com/class/25103",
            "http://dubai.flywheelsports.com/class/25104",
            "http://dubai.flywheelsports.com/class/25105",
            "http://dubai.flywheelsports.com/class/25106",
            "http://dubai.flywheelsports.com/class/25107",
            "http://dubai.flywheelsports.com/class/25108",
            "http://dubai.flywheelsports.com/class/25109",
            "http://dubai.flywheelsports.com/class/25110",
            "http://dubai.flywheelsports.com/class/25159",
            "http://dubai.flywheelsports.com/class/25112",
            "http://dubai.flywheelsports.com/class/25113",
            "http://dubai.flywheelsports.com/class/25114",
            "http://dubai.flywheelsports.com/class/25115",
            "http://dubai.flywheelsports.com/class/25116",
            "http://dubai.flywheelsports.com/class/25117",
            "http://dubai.flywheelsports.com/class/25118",
            "http://dubai.flywheelsports.com/class/25119",
            "http://dubai.flywheelsports.com/class/25120",
            "http://dubai.flywheelsports.com/class/25121",
            "http://dubai.flywheelsports.com/class/25122",
            "http://dubai.flywheelsports.com/class/25160",
            "http://dubai.flywheelsports.com/class/25161",
            "http://dubai.flywheelsports.com/class/25162",
            "http://dubai.flywheelsports.com/class/25163",
            "http://dubai.flywheelsports.com/class/25164",
            "http://dubai.flywheelsports.com/class/25165",
            "http://dubai.flywheelsports.com/class/25166",
            "http://philadelphia.flywheelsports.com/class/26482",
            "http://philadelphia.flywheelsports.com/class/26484",
            "http://philadelphia.flywheelsports.com/class/26485",
            "http://philadelphia.flywheelsports.com/class/26486",
            "http://philadelphia.flywheelsports.com/class/26487",
            "http://philadelphia.flywheelsports.com/class/26430",
            "http://philadelphia.flywheelsports.com/class/26431",
            "http://philadelphia.flywheelsports.com/class/26432",
            "http://philadelphia.flywheelsports.com/class/26433",
            "http://philadelphia.flywheelsports.com/class/26434",
            "http://philadelphia.flywheelsports.com/class/26435",
            "http://philadelphia.flywheelsports.com/class/26436",
            "http://philadelphia.flywheelsports.com/class/26439",
            "http://philadelphia.flywheelsports.com/class/26437",
            "http://philadelphia.flywheelsports.com/class/26438",
            "http://philadelphia.flywheelsports.com/class/26440",
            "http://philadelphia.flywheelsports.com/class/26441",
            "http://philadelphia.flywheelsports.com/class/26442",
            "http://philadelphia.flywheelsports.com/class/26443",
            "http://philadelphia.flywheelsports.com/class/26444",
            "http://philadelphia.flywheelsports.com/class/26445",
            "http://philadelphia.flywheelsports.com/class/26446",
            "http://philadelphia.flywheelsports.com/class/26447",
            "http://philadelphia.flywheelsports.com/class/26448",
            "http://philadelphia.flywheelsports.com/class/26449",
            "http://philadelphia.flywheelsports.com/class/26450",
            "http://philadelphia.flywheelsports.com/class/26451",
            "http://philadelphia.flywheelsports.com/class/26452",
            "http://philadelphia.flywheelsports.com/class/26515",
            "http://philadelphia.flywheelsports.com/class/26513",
            "http://philadelphia.flywheelsports.com/class/26514",
            "http://philadelphia.flywheelsports.com/class/26511",
            "http://philadelphia.flywheelsports.com/class/26512",
            "http://texas.flywheelsports.com/class/26710",
            "http://texas.flywheelsports.com/class/26711",
            "http://texas.flywheelsports.com/class/26712",
            "http://texas.flywheelsports.com/class/26713",
            "http://texas.flywheelsports.com/class/26714",
            "http://texas.flywheelsports.com/class/26715",
            "http://texas.flywheelsports.com/class/26716",
            "http://texas.flywheelsports.com/class/26717",
            "http://texas.flywheelsports.com/class/26718",
            "http://texas.flywheelsports.com/class/26719",
            "http://texas.flywheelsports.com/class/26720",
            "http://texas.flywheelsports.com/class/26721",
            "http://texas.flywheelsports.com/class/26722",
            "http://texas.flywheelsports.com/class/26723",
            "http://texas.flywheelsports.com/class/26724",
            "http://texas.flywheelsports.com/class/26725",
            "http://texas.flywheelsports.com/class/26726",
            "http://texas.flywheelsports.com/class/26727",
            "http://texas.flywheelsports.com/class/26728",
            "http://texas.flywheelsports.com/class/26729",
            "http://texas.flywheelsports.com/class/26730",
            "http://texas.flywheelsports.com/class/26731",
            "http://texas.flywheelsports.com/class/26732",
            "http://texas.flywheelsports.com/class/26733",
            "http://texas.flywheelsports.com/class/26734",
            "http://texas.flywheelsports.com/class/26735",
            "http://texas.flywheelsports.com/class/26736",
            "http://texas.flywheelsports.com/class/26737",
            "http://texas.flywheelsports.com/class/26640",
            "http://texas.flywheelsports.com/class/26641",
            "http://texas.flywheelsports.com/class/26642",
            "http://texas.flywheelsports.com/class/26643",
            "http://texas.flywheelsports.com/class/26644",
            "http://texas.flywheelsports.com/class/26645",
            "http://texas.flywheelsports.com/class/26646",
            "http://texas.flywheelsports.com/class/26647",
            "http://texas.flywheelsports.com/class/26648",
            "http://texas.flywheelsports.com/class/26649",
            "http://texas.flywheelsports.com/class/26650",
            "http://texas.flywheelsports.com/class/26651",
            "http://texas.flywheelsports.com/class/26652",
            "http://texas.flywheelsports.com/class/26653",
            "http://texas.flywheelsports.com/class/26654",
            "http://texas.flywheelsports.com/class/26655",
            "http://texas.flywheelsports.com/class/26656",
            "http://texas.flywheelsports.com/class/26657",
            "http://texas.flywheelsports.com/class/26658",
            "http://texas.flywheelsports.com/class/26659",
            "http://texas.flywheelsports.com/class/26660",
            "http://texas.flywheelsports.com/class/26661",
            "http://texas.flywheelsports.com/class/26662",
            "http://texas.flywheelsports.com/class/26663",
            "http://texas.flywheelsports.com/class/26664",
            "http://texas.flywheelsports.com/class/26665",
            "http://texas.flywheelsports.com/class/26666",
            "http://texas.flywheelsports.com/class/26667",
            "http://texas.flywheelsports.com/class/26668",
            "http://texas.flywheelsports.com/class/26669",
            "http://texas.flywheelsports.com/class/26670",
            "http://texas.flywheelsports.com/class/26671",
            "http://texas.flywheelsports.com/class/26672",
            "http://texas.flywheelsports.com/class/26673",
            "http://texas.flywheelsports.com/class/26674",
            "http://texas.flywheelsports.com/class/26675",
            "http://texas.flywheelsports.com/class/26676",
            "http://texas.flywheelsports.com/class/26677",
            "http://texas.flywheelsports.com/class/26758",
            "http://texas.flywheelsports.com/class/26759",
            "http://seattle.flywheelsports.com/class/28577",
            "http://seattle.flywheelsports.com/class/28578",
            "http://seattle.flywheelsports.com/class/28579",
            "http://seattle.flywheelsports.com/class/28580",
            "http://seattle.flywheelsports.com/class/28581",
            "http://seattle.flywheelsports.com/class/28582",
            "http://seattle.flywheelsports.com/class/28583",
            "http://seattle.flywheelsports.com/class/28584",
            "http://seattle.flywheelsports.com/class/28585",
            "http://seattle.flywheelsports.com/class/28586",
            "http://seattle.flywheelsports.com/class/28587",
            "http://seattle.flywheelsports.com/class/28588",
            "http://seattle.flywheelsports.com/class/28589",
            "http://seattle.flywheelsports.com/class/28590",
            "http://seattle.flywheelsports.com/class/28591",
            "http://seattle.flywheelsports.com/class/28592",
            "http://seattle.flywheelsports.com/class/28593",
            "http://seattle.flywheelsports.com/class/28594",
            "http://seattle.flywheelsports.com/class/28595",
            "http://seattle.flywheelsports.com/class/28596",
            "http://seattle.flywheelsports.com/class/28597",
            "http://seattle.flywheelsports.com/class/28599",
            "http://seattle.flywheelsports.com/class/28600",
            "http://seattle.flywheelsports.com/class/28728",
            "http://seattle.flywheelsports.com/class/28601",
            "http://seattle.flywheelsports.com/class/28602",
            "http://seattle.flywheelsports.com/class/28603",
            "http://seattle.flywheelsports.com/class/28604",
            "http://seattle.flywheelsports.com/class/28605",
            "http://seattle.flywheelsports.com/class/28606",
            "http://seattle.flywheelsports.com/class/28607",
            "http://seattle.flywheelsports.com/class/28608",
            "http://seattle.flywheelsports.com/class/28609",
            "http://seattle.flywheelsports.com/class/28610",
            "http://seattle.flywheelsports.com/class/28472",
            "http://seattle.flywheelsports.com/class/28473",
            "http://seattle.flywheelsports.com/class/28474",
            "http://seattle.flywheelsports.com/class/28475",
            "http://seattle.flywheelsports.com/class/28476",
            "http://seattle.flywheelsports.com/class/28477",
            "http://seattle.flywheelsports.com/class/28478",
            "http://seattle.flywheelsports.com/class/28479",
            "http://seattle.flywheelsports.com/class/28480",
            "http://seattle.flywheelsports.com/class/28481",
            "http://seattle.flywheelsports.com/class/28482",
            "http://seattle.flywheelsports.com/class/28483",
            "http://seattle.flywheelsports.com/class/28484",
            "http://seattle.flywheelsports.com/class/28485",
            "http://seattle.flywheelsports.com/class/28486",
            "http://seattle.flywheelsports.com/class/28487",
            "http://seattle.flywheelsports.com/class/28488",
            "http://seattle.flywheelsports.com/class/28489",
            "http://seattle.flywheelsports.com/class/28490",
            "http://seattle.flywheelsports.com/class/28491",
            "http://seattle.flywheelsports.com/class/28492",
            "http://seattle.flywheelsports.com/class/28493",
            "http://seattle.flywheelsports.com/class/28494",
            "http://seattle.flywheelsports.com/class/28495",
            "http://seattle.flywheelsports.com/class/28496",
            "http://seattle.flywheelsports.com/class/28497",
            "http://seattle.flywheelsports.com/class/28498",
            "http://seattle.flywheelsports.com/class/28499",
            "http://seattle.flywheelsports.com/class/28500",
            "http://seattle.flywheelsports.com/class/28501",
            "http://seattle.flywheelsports.com/class/28502",
            "http://seattle.flywheelsports.com/class/28503",
            "http://seattle.flywheelsports.com/class/28504",
            "http://seattle.flywheelsports.com/class/28505",
            "http://seattle.flywheelsports.com/class/28506",
            "http://seattle.flywheelsports.com/class/28507",
            "http://seattle.flywheelsports.com/class/28508",
            "http://seattle.flywheelsports.com/class/28509",
            "http://seattle.flywheelsports.com/class/28510",
            "http://seattle.flywheelsports.com/class/28511",
            "http://seattle.flywheelsports.com/class/28512",
            "http://seattle.flywheelsports.com/class/28513",
            "http://seattle.flywheelsports.com/class/28514",
            "http://seattle.flywheelsports.com/class/28515"];

function follow(user, callback) {
    var page = require('webpage').create();
    page.open(user, function (status) {
        if (status === 'fail') {
            console.log(user + ': ?');
        } else {
            var count = page.evaluate(function () {
                return document.querySelectorAll('.reserved').length - 1;
            });

            var time = page.evaluate(function () {
                return document.querySelectorAll('.reserve_main_table td')[2].innerText +
                       ' ' +
                       document.querySelectorAll('.reserve_main_table td')[3].innerText;
            });

            var loc = page.evaluate(function () {
                return document.querySelectorAll('.reserve_main_table td')[4].innerText;
            });
            console.log([user, loc, time, count].join('\t'));
        }
        page.close();

        if (callback) {
            callback();
        }
    });
}

function process() {
    phantom.addCookie({
        'name':     'SESS0503627fa9caee1704074bff31525611',
        'value':    '2521fe797adf8ef2f485fc57a8ec11f4',
        'domain':   '.flywheelsports.com'
    });

    if (users.length > 0) {
        var user = users.pop();
        follow(user, process);
    } else {
        phantom.exit();
    }
}

process();
